@server = http://localhost:3000
### 회원가입

POST {{server}}/auth/register
Content-Type: application/json

{
    "email" : "andy1@podo.com",
    "password" : "1234",
    "username" : "andy"
}

### 로그인
POST {{server}}/auth/login
Content-Type: application/json

{
    "email" : "andy1@podo.com",
    "password" : "1234"
}